### ISSUE TITLE
Future of vulnerability scanner....

### ISSUE THREAD

**Issue by TheLastCicada** [markri/wp-sec#10]
So.... funny story..... we at 10up were building a wp-cli vulnerability scanner at the same time you were building this.  https://github.com/10up/wp-vulnerability-scanner.  Our tools do pretty much the same thing (I've been using both and like the way yours displays some information, but also like how ours can do checks on specific plugin and theme versions).  We started a conversation with Daniel Bachhuber about adding our vulnerability scanner to the package index and Daniel is preferring having a canonical solution rather than a bunch of different packages solving the same problem https://github.com/wp-cli/package-index/pull/98.  I think that approach makes sense, so I'm wondering if we can collaborate here on a single vulnerability/security wp-cli plugin going forward.  Not sure yet what that looks like, but we're committed to maintaining this and I think a combined wp-cli package with the functionality of both of our tools would be a great thing.  

Let me know what you think.  @tott has been working on this with me and will be joining in the conversation as well.

**Comment by danielbachhuber** [comment]
Just wanted to weigh in that I'm happy to help out in any way I can. A couple of ideas I've had include:

* Drafting guidelines / best practices for community packages.
* Creating an organization (or using the existing WP-CLI organization) for packages maintained by multiple developers.

Open to suggestions!

**Comment by tott** [comment]
Thanks @danielbachhuber and nice to get in touch again. Let's see what @markri thinks of this and see how we can best approach this.

**Comment by markri** [comment]
@danielbachhuber @TheLastCicada @tott 

Definitely interesting! In my opinion this is what open source is all about :-)

I understand the need of a healthy index with some curation, although on the other hand I think it limits creativity. For now it seems that both packages accomplish the same thing, but its hard to say if it will stay that way. If we decide to "kill" one package in favour of the other it might also kill the motivational attitude for creating new features and possibilities of other packages.

I'd like to think big here, Packagist like. There will be many packages and a lot of these have similarities and some of them might be almost identical, but is that a problem? I'd prefer to let the end-user decide which package to choose. Eventually things like popular votes, number of downloads, active development and updates will decide which package is preferred by the community. (let it grow organically, but control the outer structure by building a platform that supports the end user in picking a package)

And of course, if a bigger (more automated) platform is the way to go; I would be glad to help out

**Comment by danielbachhuber** [comment]
@markri Thanks for the thoughts.

It might be that we agree to disagree, but I actually see Packagist (and the WordPress.org plugins directory) as hugely problematic from a user's perspective. Sure, there can be lots of options to choose from but, most of the time, the options aren't healthy, actively maintained projects. From a user's perspective, this is a horrible experience — "I have a problem I need a solution for, there are three options, each is in a state of disrepair, and I can even see when each project was created in response to an older one being abandoned".

For the WP-CLI Package Index, I'm actively addressing this problem. My expectation is that the listed packages meet or exceed the standards users have come to expect of WP-CLI. WP-CLI doesn't bundle two slightly differently implementations of the same command because that wouldn't make any sense at all. Similarly, in the package index, it makes more sense to have one actively maintained implementation, than it does two or three partially abandoned implementations. And, by making shared maintenance responsibilities one of the goals, we reduce the likelihood of abandonment through attrition.

With this being said, there are plenty of other distribution means (including installing packages directly from Github) for the bazaar approach to exist too.

At this point, I see some options as:

1. Pick `markri/wp-sec` as the canonical implementation of a plugin vulnerability check, and don't list the 10up implementation.
2. Pick the 10up implementation as the canonical, and delist `markri/wp-sec`.
3. Create a new `wp-cli/security-command` or similar repo for a new canonical implementation.
4. Start a conversation in `wp-cli/wp-cli` about drafting a set of package index guidelines, and proceed to a decision from there.

Please understand I don't mean personal offense here. I'm having the same conversation with a few different groups now (https://github.com/wp-cli/package-index/pull/90, https://github.com/wp-cli/package-index/pull/93, https://github.com/wp-cli/package-index/pull/95). Here are some things I've written on the topic in the past:

* https://github.com/wp-cli/wp-cli/issues/3197
* [My condolences, you’re now the maintainer of a popular open source project](https://runcommand.io/2016/06/26/my-condolences-youre-now-the-maintainer-of-a-popular-open-source-project/)

**Comment by tott** [comment]
While I also see the points @markri outlined in terms of the spirit of open source and heaving a healthy set of choices I also need to agree with @danielbachhuber as I've seen way too many bad options being available in the public repositories making it hard for the average user to decide which option is best. In my opinion for this particular issue the solution seems to be simple to me as we're both trying to cover a pretty defined use-case. I think it would be best to just merge our efforts in a new repository which we all can contribute on. We could easily merge our feature set and code base and given that we're both able to address upcoming issues I also think it would be the best result for the community.

**Comment by markri** [comment]
I don't want to offend anyone either and no offense taken :-)

First of all, I'd like to elaborate about my intentions with wp-sec, so we can understand each other better. Wp-sec came with a history (https://markri.nl/wordpress-cve-scanner/) which eventually resulted in wp-sec. So there is already quite some time in it from my side.

By creating this (with the the company I work for in mind), I also wanted it to be open source so others could use it too. Another reason (and I'm trying not be ashamed of it, but I'm confident enough that many people will recognize this) is to take some pride in it having my name mentioned somewhere to build up some authority. I have never seen repository contributions done anonymously, or even the option to do so, and I think that is a humble fee to ask for when publishing free software.

I have read your blog about open source projects and "first class citizens in wp-cli index", which is definitely worth reading and fully understandable. But I think it can also kill motivation for contributing so much needed new ideas to already existing open-source projects, which results in slow growing of the package index (but great quality).

This also results in a tough and sometimes even a rough job to be able to distinguish what's new (and is to be added to the package index) and what not. And what to decide between not so clear cases. Comparing code quality, functionality, intentions/aspirations, active development, maybe even people, etc. Maybe two different packages in the future will collide and things may become not so clear. 

Another example; what to do if a new package comes into existence which is more feature rich and better than an existing package, because the new author found it easier to start from scratch than refactor and add features? Would it be "fair" to reject that, or would one kick out the old package in favour of the new one? 

That's why I think that regulating is better than dictating (not that anyone is doing that right now, but there will surely be dilemmas in the future where decisions are needed).

For the current situation:
The middle path in this would seemingly be to create a new repository on which both parties work on, just to create equality between both parties. However, this takes a bit out of the fun and motivation for me. First of all the repository is no longer on my Github (which gives  me some authority) and my domain at http://wp-sec.org would also have to go.

Therefore, sorry to say, I choose my side (1st option, hope you all understand). This way we can still address the collaborative growth and the canonical approach. I suggest the native GitHub pull request workflow, in which I can create PR's on my own repo for others to review as well (if wanted).
