### ISSUE TITLE
plugin list failing due to lack of memory

### ISSUE THREAD

**Issue by cericoda** [markri/wp-sec#13]
Hello, your plugin is great. I have taken to launching wp-sec with the following:-

`php -d memory_limit=512M  /usr/local/bin/wp wp-sec check  --allow-root --path=/home/$CPUSER/public_html
`

Unfortunately, for one particular site, I am unable to get a list of plugins

this command passes, with the expected list of plugins: 
`php -d memory_limit=512M /usr/local/bin/wp plugin list   --allow-root --path=/home/$CPUSER/public_html`

but this one fails:
 `/usr/local/bin/wp plugin list   --allow-root --path=/home/$CPUSER/public_html`

Not even sure if this is a bug but thought I would put it here in case anyone has any suggestions or comments.

**Comment by markri** [comment]
Hi cericoda,

It seems like the memory limit isn't passed to WP_CLI::launch_self() by my extension

Normally it would be the same runtime environment, but it appears that eventually another proc_open is done in 
https://github.com/wp-cli/wp-cli/blob/fa8e74d74fa49a71f04911d832f74e17e855eae0/php/WP_CLI/Process.php#L43

Which is why the memory limit from the current runtime environment isnt passed

However it is possible to add this as an extra argument in $args 
https://github.com/wp-cli/wp-cli/blob/fa8e74d74fa49a71f04911d832f74e17e855eae0/php/class-wp-cli.php#L959

So what needs to be done is to replace the second array in all instances of WP_CLI::launch_self() in
https://github.com/markri/wp-sec/blob/master/command.php
with the command args that is originally entered. (not sure if this will conflict with anything)

Maybe this is something you can test and create a PR for?

**Comment by cericoda** [comment]
Hi markri

I'd be very happy to make the changes and test them, and create a PR for approval, but how can I pass the arguments as entered? 

Is it as simple as $output = WP_CLI::launch_self('core is-installed', $ags, array(), false, true);

**Comment by cericoda** [comment]
Hi markri

I tried 

`$output = WP_CLI::launch_self('core is-installed', $ags, array(), false, true); `

but it made no difference.

**Comment by markri** [comment]
Just launched my setup again to see if I could be of any help. But then I realized it's due to the structure of wp-cli itself. It's commands are reusable, but IMHO not executed in a decent way. It shouldn't be executed throug proc_open. But that's just the way it is.

So even if adding memory_limit through args would be working, it would be the wrong solution (sorry about that). Next day someone will be asking to add another option like error_reporting = E_ALL instead of E_ALL ~ E_DEPRECATED (or whatever config suits their needs). And adding every ini variable through $args would be just yuckiness all over. So taking a second though on this, I wouldnt want to pass along ini variables.

So what to do then?
Thinking about a situation how this issue would occur; I think you might be using a shared php.ini config which used in CLI and through your webserver. You might want to split them up by creating a `php-cli.ini`. So you don't need to override the memory_limit and have the same working environment for every PHP command that is executed

**Comment by cericoda** [comment]
No worries- happy to close this and will find another way round it. Thanks.

**Comment by cericoda** [comment]
Just a short note on how I achieved this, in cpanel, as we only wanted to affect root's CLI PHP memory, I had to add a suitable ini file only readable by root in /opt/cpanel/ea-php56/root/etc/php.d/
